# Copyright (c) 2022 Espresso Systems (espressosys.com)
# This file is part of the surf-disco library.
#
# You should have received a copy of the MIT License
# along with the surf-disco library. If not, see <https://mit-license.org/>.

name: Windows build

on:
  push:
    branches:
      - main
      - release-*
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-2022
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@v2
        name: Enable Rust Caching

      - name: Build
        run: |
          cargo build --workspace --release

      - name: Test
        run: |
          cargo test --workspace --release --no-run
          cargo test --workspace --release --verbose -- --test-threads 2
        timeout-minutes: 30
