name: Code Coverage

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-latest
    env:
        RUST_LOG: info
        RUSTFLAGS: "--cfg async_executor_impl=\"async-std\" --cfg async_channel_impl=\"async-std\""
    steps:
      - uses: actions/checkout@v4
        name: Checkout Repository

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Enable Rust Caching
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Generate code coverage
        run: |
          mkdir coverage
          cargo llvm-cov --workspace --lcov --output-path ./coverage/lcov.info
        timeout-minutes: 240

      - name: Coveralls upload
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
